### ISSUE TITLE
Requesting access to source code for OpenRTX binary and related tools

### ISSUE THREAD

**Issue by RadioEnthused** [Tunas1337/Talkpod-A36Plus-SDK#1]
Hello @Tunas1337. I'm not sure if GitHub sends notification from commit comment after it is merged, so I open this issue to be safe.
I write the request here: https://github.com/VR2TE/Talkpod-A36plus-Firmware/commit/9c0aeab691cfdfacd3cf4aea74487b78b05457b6

Thx.

**Comment by Tunas1337** [comment]
For the benefit of anyone who stumbles upon this, and not the commit comment, I will also copy-paste the answer here.

You can find the source code under the "A36Plus" branch of my fork of OpenRTX: https://github.com/Tunas1337/OpenRTX/tree/A36Plus

Building a .kdhx is done with the rtxflash utility, which currently has a pending pull request for A36Plus support in both wrapping (creating a .kdhx) and flashing the binary, in a separate branch. That can be found at https://github.com/OpenRTX/rtxflash/tree/a36plus
Alternatively, you can use the encrypt.c utility in amoxu's repository (https://github.com/amoxu/Baofeng-UV-5RM-5RH-RE/blob/main/reverse_engineering/encrypt.c) That only creates a kdhx file, and you can use the TalkpodBootloader to flash it.

Please make sure you checkout the specific branches for the A36plus, as this work isn't mainlined quite yet in either case.

Thank you for your interest!
